version: '3'
services:
  nginx:
    env_file:
    - .env
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
      - ./nginx/templates:/etc/nginx/templates
    ports:
    - "80:80"
    - "443:443"
  certbot:
    container_name: certbot
    image: certbot/certbot:v2.6.0
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    command: ["--version"]
  tenso-kun:
    env_file:
      - .env
    container_name: tenso-kun
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/opt/
    ports:
    - "5000:5000"
    command: ./tenso-kun
